version: "3.8"
services:
  api:
    restart: "always"
    env_file: ".env"
    build:
      context: "."
      dockerfile: "./Dockerfile.dev"
    depends_on:
        - postgres
    ports:
      - "9000:9000"
    volumes:
      - "./src:/app/src"
      - "./prisma:/app/prisma"

  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${DATABASE_USERNAME}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=${DATABASE_NAME}"
